[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"


[tool.poetry]
name = "pytarkbot"
version = "v0.0.0"
description = "Automated Tarkov"
readme = "README.md"
authors = [
  "Matthew Miglio <matthew@martinmiglio.dev>",
  "Martin Miglio <code@martinmiglio.dev>",
]
homepage = "https://matthewmiglio.github.io/py-TarkBot"
repository = "https://github.com/matthewmiglio/py-TarkBot"
documentation = "https://matthewmiglio.github.io/py-TarkBot"
classifiers = [
  "Intended Audience :: End Users/Desktop",
  "Environment :: Win32 (MS Windows)",
  "License :: OSI Approved :: MIT License",
  "Natural Language :: English",
  "Operating System :: Microsoft :: Windows",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Topic :: Games/Entertainment",
]
keywords = ["tarkov", "bot", "automation"]
include = ["README.md", "pytarkbot/detection/reference_images/**/*.png"]


[tool.poetry.dependencies]
python = "^3.10"
pillow = "^9.4.0"
pysimplegui = "^4.60.4"
pyautogui = "^0.9.53"
numpy = "^1.24.2"
pygetwindow = "^0.0.9"
opencv-python = "^4.7.0.72"
joblib = "^1.2.0"
requests = "^2.28.2"
bs4 = "^0.0.1"
pytesseract = "^0.3.10"


[tool.poetry.group.build]
optional = true


[tool.poetry.group.build.dependencies]
cx-logging = "^3.1.0"
Cx_Freeze = [{ version = "^6.14.7", platform = 'win32' }]


[tool.poetry.group.dev]
optional = true


[tool.poetry.group.dev.dependencies]
pre-commit = "^3.2"
black = "^23.3.0"
ipykernel = "^6.21.3"
matplotlib = "^3.7.1"
vulture = "^2.7"


[tool.black]
line-length = 88
target-version = ['py310']
include = '\.pyi?$'
exclude = '''
(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
  )/
)
'''


[tool.isort]
profile = "black"


[tool.pylint.main]
ignore = ["build", "debug.py"]
py-version = "3.10"
suggestion-mode = true
disable = [
  "C0114", # missing-module-docstring
  "C0115", # missing-class-docstring
  "C0116", # missing-function-docstring
  "C0301", # line-too-long
  "C0103", # invalid-name
]
extension-pkg-whitelist = "win32gui"
