[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"


[tool.poetry]
name = "pytarkbot"
version = "v0.0.0"
description = "Automated Tarkov"
readme = "README.md"
authors = [
  "Matthew Miglio <matthew@martinmiglio.dev>",
  "Martin Miglio <code@martinmiglio.dev>",
]
homepage = "https://matthewmiglio.github.io/py-TarkBot"
repository = "https://github.com/matthewmiglio/py-TarkBot"
documentation = "https://matthewmiglio.github.io/py-TarkBot"
classifiers = [
  "Intended Audience :: End Users/Desktop",
  "Environment :: Win32 (MS Windows)",
  "License :: OSI Approved :: MIT License",
  "Natural Language :: English",
  "Operating System :: Microsoft :: Windows",
  "Programming Language :: Python :: 3.10",
  "Topic :: Games/Entertainment",
]
keywords = ["tarkov", "bot", "automation"]
include = ["README.md", "pytarkbot/detection/reference_images/**/*.png"]


[tool.poetry.dependencies]
python = "^3.10.0"
pillow = "^9.3.0"
pyperclip = "^1.8.2"
PySimpleGUI = "^4.60"
pyautogui = "^0.9"
numpy = "^1.21.4"
pygetwindow = "^0.0"
pytesseract = "^0.3.8"
screeninfo = "^0.6.7"
opencv-python = "^4.6.0"
joblib = "^1.2"
pandas = "^1.3.4"
tqdm = "^4.62.3"
requests = "^2.28"
urllib3 = "^1.26.12"
pywin32 = "^305"
lxml = "^4.9.1"


[tool.poetry.group.build]
optional = true


[tool.poetry.group.build.dependencies]
cx-logging = "^3.1.0" # specify version of cx_logging for cx_freeze to run with python 3.11
Cx_Freeze = "^6.13.1"


[tool.poetry.group.dev]
optional = true


[tool.poetry.group.dev.dependencies]
pre-commit = "^2.20"
black = "^22.10.0"
ipykernel = "^6.17.1"
matplotlib = "^3.4.3"


[tool.black]
line-length = 88
target-version = ['py310']
include = '\.pyi?$'
exclude = '''
(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
  )/
)
'''


[tool.isort]
profile = "black"


[tool.pylint.main]
ignore = ["build", "debug.py"]
py-version = "3.10"
suggestion-mode = true
disable = [
  "C0114", # missing-module-docstring
  "C0115", # missing-class-docstring
  "C0116", # missing-function-docstring
  "C0301", # line-too-long
  "C0103", # invalid-name
]
extension-pkg-whitelist = "win32gui"
