"""Flea Snipe mode: watch the flea for items listed under what a trader pays for them.

The opposite trade to sell_bot.py. That one takes an item out of the stash and lists it;
this one walks a watchlist of item names, searches each on the flea, reads the cheapest
offer, and buys it when the asking price is far enough under trader value to be worth the
click. The item is then sold to the trader by hand, which is why nothing here goes near a
trader screen.

The watchlist is snipe_targets.csv beside this file, generated by _price_scraper/ from
tarkov-market.com. Roubles only, both legs: every row has a rouble trader price, and the flea
is roubles anyway. Peacekeeper's dollar prices are dropped at scrape time, not here. Every sweep
walks the whole list in a fresh random order, so no item is checked at the same point of every
cycle and none of them is always last.

One pass over one item, which is what check_one does:

    type the name into the flea's search box, wait for the suggestion list
    if a padlock is showing in that quarter of the window, empty the box and move on
    otherwise click the suggestion, then click back into the box and empty it
    wait for the board, read the price on the topmost offer row
    if it is at least MARGIN roubles under what the trader pays, buy that row

The filters are set once per sweep rather than once per item. They survive a search, and
opening that window costs four matches and three menu waits, which is most of a minute across
a whole watchlist.
"""
import csv
import random
import threading
import time
from pathlib import Path

import screen
import tarkov_window
from interact import snipe  # everything this mode does to a screen goes through that module
from narrate import log
from sell_bot import Stopped  # shared runner plumbing, see the note on _pause below

# The watchlist, beside this module so the frozen build finds it the way find.py finds its
# reference images. scripts/setup_msi.py copies it to lib/snipe_targets.csv.
TARGETS_PATH = Path(__file__).parent / 'snipe_targets.csv'

# How many roubles under trader value an offer has to be listed before it is worth buying. GUI
# label -> roubles, so the dropdown, the saved setting and the test all read off one definition.
# A flat cut rather than a percentage, because what makes a flip worth the clicks is the profit
# on it and not the ratio: 10% off a 2000 rouble barter item is 200 roubles for the same six
# actions that clear 9000 on a scope.
MARGINS = {'500 rubles': 500,
           '1k rubles': 1000,
           '2k rubles': 2000,
           '5k rubles': 5000}
DEFAULT_MARGIN = '500 rubles'

# The GUI's TRADER dropdown: buy only what one trader will buy back, or everything. Narrowing it
# is not about the money, it is about the selling afterwards being done by hand. A run that
# brings home 26 items for Therapist and 2 for Jaeger is a run where the two are easy to miss,
# and an item sold to the wrong trader pays less: on 2026-08-17 two Jaeger scopes worth 54,894
# went to a trader that was not Jaeger, and most of that run's missing profit went with them.
ALL_TRADERS = 'All traders'
# Therapist rather than everything, because everything is the setting that caused the problem.
# 70 of the 77 items on the watchlist are Therapist's, so the default gives up 7 of them and
# removes a whole class of mistake at the selling end. Pick ALL_TRADERS deliberately if the
# extra handful is worth keeping track of.
DEFAULT_TRADER = 'Therapist'

# A listing this far under trader value is treated as a misread rather than a bargain. Nothing
# on the flea is a quarter of what a trader pays for it, and the ways a price read can go wrong
# all go wrong downwards: a crop that cuts the leading digits turns 128,000 into 000. Left as a
# fraction of trader value rather than a flat floor so it scales with the item.
# interact/snipe.read_price refuses a clipped box outright; this is the backstop for the reads
# that come back looking sane.
SANITY_FLOOR = 0.25

SWEEP_PAUSE = 2.0  # seconds between full passes of the watchlist, so the board is not hammered

# The counters snipe mode keeps, in the order the GUI lists them. Same shape as
# sell_bot.STAT_LABELS and gym_bot.STAT_LABELS so the GUI draws all three from one code path.
STAT_LABELS = (('checked', 'Offers checked'),
               ('locked', 'Locked, skipped'),
               ('price_missing', 'Prices unreadable'),
               ('hits', 'Under trader value'),
               ('bought', 'Items bought'),
               ('buy_failed', 'Buys that missed'),
               ('spent', 'Roubles spent'),
               ('trader_value', 'Trader value bought'),
               ('profit', 'Profit'))
# The row the GUI tints green once it is non-zero. sell_bot names 'money' and gym_bot 'reps';
# here the "it is actually working" signal is the same one selling uses, roubles made, which
# for a buyer is what the traders will pay for the pile less what it cost to buy it.
TINT_STAT = 'profit'


def targets(path=TARGETS_PATH):
    """The watchlist as [(name, trader, trader_price)], in the file's own order.

    Not shuffled here: sweep_once does that, so every sweep gets a fresh order rather than one
    order picked at startup and repeated for the rest of the session.

    Returns an empty list if the file is missing, and says so. A sniper with no watchlist is a
    thing to report, not to crash over: the csv is generated, so a build that shipped without
    it should still open and still tell the user why nothing is happening.
    """
    if not Path(path).is_file():
        log(f'no watchlist at {path}, so there is nothing to snipe')
        return []
    with Path(path).open(encoding='utf-8', newline='') as handle:
        return [(row['Name'], row['Trader'], int(row['Trader price']))
                for row in csv.DictReader(handle)]


def trader_choices(path=TARGETS_PATH):
    """What the GUI's TRADER dropdown offers: 'All traders', then every trader on the watchlist.

    Read off the csv rather than written out here, so a watchlist regenerated with a different
    spread of traders offers the right ones without anybody remembering to edit a list. Ordered
    by how many items each one buys, since a trader with 70 rows on the list is a more useful
    pick than one with a single row and should not be sorted underneath it.
    """
    counts = {}
    for _, trader, _ in targets(path):
        counts[trader] = counts.get(trader, 0) + 1
    ranked = sorted(counts, key=lambda name: (-counts[name], name))
    return [ALL_TRADERS, *ranked]


def for_trader(watchlist, trader):
    """`watchlist` cut down to one trader's items, or left alone for ALL_TRADERS."""
    if trader == ALL_TRADERS:
        return watchlist
    return [row for row in watchlist if row[1] == trader]


class FleaSniper:
    def __init__(self, margin=MARGINS[DEFAULT_MARGIN], watchlist=None, stats=None):
        log('Initalizing Flea Sniper')
        self.hwnd = tarkov_window.handle()  # raises WindowError if missing or duplicated
        self.position = tarkov_window.position(self.hwnd)
        self.size = tarkov_window.size(self.hwnd)
        self.monitor = screen.current()
        # The window clipped to the chosen monitor, the same rule and the same reason as
        # Tarkbot.__init__: the window alone is wrong when the user picked a screen the game is
        # not on, the monitor alone is wrong when the game is windowed.
        self.region = screen.overlap(self.position + self.size, self.monitor.rect)
        if self.region is None:
            raise tarkov_window.WindowError(
                f'Tarkov is at {self.position + self.size}, which is not on monitor '
                f'{self.monitor.label} at {self.monitor.rect}. Pick the other monitor, or move '
                f'the game onto this one.')
        self.margin = margin  # fraction under trader value an offer has to be, see MARGINS
        self.watchlist = targets() if watchlist is None else watchlist
        log(f'Tarkov window {self.hwnd} at {self.position} size {self.size}')
        log(f'monitor {self.monitor.label} ({self.monitor.name}) at {self.monitor.rect}, '
            f'searching {self.region}', 1)
        log(f'{len(self.watchlist)} items on the watchlist, buying anything listed {self.margin:,} '
            f'roubles or more under trader value', 1)
        # The GUI hands in its own dict so the counters span the session, exactly as the other
        # two modes do. Nothing passed, count from zero.
        self.stats = {key: 0 for key, _ in STAT_LABELS} if stats is None else stats
        self._stop = threading.Event()
        self._search_box = None  # where the search box was last seen, see snipe.find_search_box

    def _pause(self, seconds=0):
        """Wait, or drop out of the loop right now if stop() has been called.

        ponytail: the third copy of Tarkbot._pause, and the one that settles it. gym_bot's copy
        already says to hoist _pause, _stop and stop() into a Runner the moment a third mode
        turns up. This is that mode. Do it before any of the three grows a checkpoint the other
        two do not have.
        """
        if self._stop.wait(seconds):  # wait(0) is just a check, no sleep
            raise Stopped()

    def worth_buying(self, asking, trader_price):
        """True if `asking` is at least self.margin roubles under what the trader pays.

        The whole decision, kept as one function with no screen in it so it can be checked
        without a game: everything else in a pass is finding the two numbers to hand it.

        SANITY_FLOOR is the second half of it and not an optimisation. A price read can only
        really go wrong downwards, since every failure mode drops digits rather than adding
        them, and downwards is the direction that makes this function say yes. So a listing
        under a quarter of trader value is refused as a misread, at the cost of walking past a
        bargain that would have to be the best one anybody has ever seen on the flea.
        """
        if asking < trader_price * SANITY_FLOOR:
            log(f'{asking:,} is under {SANITY_FLOOR:.0%} of the {trader_price:,} a trader pays, '
                f'which is a misread and not a bargain; not buying it', 1)
            return False
        return trader_price - asking >= self.margin

    def check_one(self, name, trader, trader_price):
        """Search one item, read the top offer's price, buy it if it is worth buying.

        True if something was bought. Counts into stats either way, because "checked 90 and
        bought nothing" and "checked 4 and bought nothing" are different runs and the log
        should not read the same for both.

        The board is read through the topmost PURCHASE button rather than through a region of
        its own. The button is the only thing on an offer row with a reference crop, the price
        sits at a fixed offset from it (see interact/snipe.PRICE_LEFT), and finding it is
        already needed to click it, so one match does both jobs.
        """
        self.stats['checked'] += 1
        # Remembered across items on purpose: the box only matches while it is empty, so a
        # clear that did not take would otherwise end the sweep. See snipe.find_search_box.
        box = snipe.find_search_box(self.region, self._search_box)
        if box is None:
            return False
        self._search_box = box
        if snipe.search_for(name, box, self.region) is None:
            self.stats['locked'] += 1
            log(f'{name}: locked, so it is not for sale to us', 1)
            return False
        self._pause(snipe.BOARD_DELAY)  # the board reloading, and a Stop can land in it

        buttons = snipe.purchase_buttons(self.region)
        if not buttons:
            log(f'{name}: no offers on the board', 1)
            return False
        top = buttons[0]  # topmost, which is the cheapest once the board is sorted by price
        asking = snipe.read_price(top)
        if asking is None:
            self.stats['price_missing'] += 1
            log(f'{name}: no readable price on the top offer', 1)
            return False

        under = trader_price - asking
        if not self.worth_buying(asking, trader_price):
            log(f'{name}: top offer {asking:,} against {trader} at {trader_price:,} '
                f'({under:+,} roubles of margin, want {self.margin:,}), leaving it', 1)
            return False

        log(f'{name}: top offer {asking:,} is {under:,} under {trader} at {trader_price:,}')
        self.stats['hits'] += 1
        # Counted on the balance moving, not on the click going out. Those are not the same
        # thing: on 2026-08-17 this counted 55,000 roubles of purchases whose confirmation
        # dialogs were still sat unanswered on screen, and every stat downstream inherited it.
        if not snipe.buy(top, self.region):
            self.stats['buy_failed'] += 1
            log(f'{name}: the purchase did not go through, so it is not being counted', 1)
            return False
        self.stats['bought'] += 1
        self.stats['spent'] += asking
        self.stats['trader_value'] += trader_price
        # Profit is what the traders will pay for everything bought, less what it cost to buy.
        # Counted here rather than worked out in the GUI so the number and the two it comes from
        # can never drift: one place adds all three.
        self.stats['profit'] += under
        return True

    def sweep_once(self):
        """One pass over the whole watchlist. How many items it bought.

        The filters go on once here rather than once per item: they survive a search, and the
        window costs four matches and three menu waits to open and close. A filter-by-item is
        cleared straight afterwards if one survived them.

        Shuffled, and reshuffled every sweep. Every name still gets looked at exactly once per
        sweep, so a sweep is the same amount of work whatever order it runs in; what changes is
        that the same item is not checked at the same point of every cycle. Walking the csv's own
        order would mean the top of the list gets read every few minutes on the dot and the
        bottom of it always waits the longest, which is both a pattern in the clicking and a
        standing head start for whoever else is watching the same items.
        """
        if not snipe.apply_flea_filters(self.region):
            log('the filters would not go on, so the board cannot be trusted; skipping this sweep')
            return 0
        # And again after them, not only at Start. The filter window's reset can bring a saved
        # filter set back with it, and a board still filtered to one item answers every search
        # with that item, which reads as 77 checks and is really one.
        if snipe.remove_filter_by_item_filter(self.region):
            log(f'the board came out of the filter window still filtered by item; cleared it '
                f'and giving it {snipe.BOARD_DELAY}s to reload')
            self._pause(snipe.BOARD_DELAY)  # a Stop can land in that wait

        order = random.sample(self.watchlist, len(self.watchlist))  # a shuffled copy, not in place
        bought = 0
        for name, trader, trader_price in order:
            self._pause()  # a Stop lands between items, not at the end of the list
            bought += self.check_one(name, trader, trader_price)
        return bought

    def start(self):
        """Sweep the watchlist over and over until stop() is called. Blocks, so give it a thread.

        A sweep is the whole list: all 77 names, one after another, and then straight back to
        the top for another 77 in a fresh order. There is no end to it but Stop. The board is
        opened once, up here, rather than once per sweep, since nothing in a sweep closes it.
        """
        log('Starting Flea Sniper')
        self._stop.clear()
        if not self.watchlist:
            log('nothing to watch, so there is nothing to do')
            return
        sweeps = 0
        started = time.perf_counter()
        try:
            # Opens, escapes, opens again so the filter chips come back to the front of the
            # header, then clears a leftover filter-by-item if one is showing. A board still
            # filtered to one item would answer every search with that item.
            if not snipe.open_clean_board(self.region):
                log('the flea did not open, so there is no board to read')
                return
            while not self._stop.is_set():
                sweeps += 1
                log(f'===== sweep {sweeps} =====')
                self.sweep_once()
                self._pause(SWEEP_PAUSE)
        except Stopped:
            log('stopped part way through a sweep')
        finally:
            # finally, for the same reason as the other two modes: an error out of a sweep is
            # not caught here, and the totals are worth more on a crashed run than a clean one.
            log(f'Flea Sniper finished after {sweeps} sweeps and '
                f'{time.perf_counter() - started:.0f}s. '
                + ', '.join(f'{label} {self.stats[key]}' for key, label in STAT_LABELS))

    def stop(self):
        """Ask the loop to quit. Safe from any thread, and safe to call twice."""
        log('Stopping Flea Sniper')
        self._stop.set()


def build(prefs, stats):
    """A FleaSniper configured from the GUI's saved preferences.

    Here rather than in the GUI so the mapping from a settings key to a constructor argument
    sits beside the constants those keys index into, the same as sell_bot.build() and
    gym_bot.build(). The GUI calls whichever the active tab names.
    """
    screen.use(prefs.get('monitor', screen.AUTO))  # before the runner, which clips to it
    margin = MARGINS.get(prefs.get('margin'), MARGINS[DEFAULT_MARGIN])
    trader = prefs.get('trader', DEFAULT_TRADER)
    watchlist = for_trader(targets(), trader)
    if trader != ALL_TRADERS:
        log(f'watching only what {trader} buys back: {len(watchlist)} of {len(targets())} items')
    return FleaSniper(margin=margin, watchlist=watchlist, stats=stats)


if __name__ == '__main__':
    # The margin test and the watchlist reader are the two bits of this module that are real
    # and can go wrong quietly, so they get the one runnable check. No game needed.
    sniper = FleaSniper.__new__(FleaSniper)  # no window, no monitor, just the decision
    sniper.margin = 500
    assert sniper.worth_buying(99_500, 100_000), 'exactly 500 under is worth buying'
    assert sniper.worth_buying(50_000, 100_000), 'far under is worth buying'
    assert not sniper.worth_buying(99_501, 100_000), 'a rouble short of the margin is not'
    assert not sniper.worth_buying(120_000, 100_000), 'above trader value is never worth it'
    # The misread backstop. A crop that cuts the leading digits off 128,000 reads as 000 or
    # 8,000, which clears the margin by miles and is the one shape of wrong answer that spends
    # money on its own.
    assert not sniper.worth_buying(8_000, 100_000), 'a quarter of trader value is a misread'
    assert sniper.worth_buying(25_000, 100_000), 'and the floor itself still buys'

    # The trader filter, which decides what a run even looks at.
    sample = [('a', 'Therapist', 100), ('b', 'Jaeger', 200), ('c', 'Therapist', 300)]
    assert for_trader(sample, ALL_TRADERS) == sample, 'all traders means the whole list'
    assert for_trader(sample, 'Jaeger') == [sample[1]], 'one trader means only their items'
    assert for_trader(sample, 'Prapor') == [], 'a trader with nothing on the list gets nothing'

    rows = targets()
    assert rows, f'no watchlist at {TARGETS_PATH}'
    choices = trader_choices()
    assert choices[0] == ALL_TRADERS, 'all traders comes first'
    assert set(choices[1:]) == {trader for _, trader, _ in rows}, 'every trader is offered'
    # Busiest first: picking the trader with 70 items should not mean scrolling past one with 1.
    counts = [len(for_trader(rows, name)) for name in choices[1:]]
    assert counts == sorted(counts, reverse=True), 'traders are offered busiest first'
    assert all(price > 0 for _, _, price in rows), 'every row needs a rouble trader price'
    # The names get typed into the flea's search box, so a breadcrumb or a required level left
    # on the end of one is a search that finds nothing and an item silently never checked.
    assert all(name and 'Req lvl' not in name for name, _, _ in rows), 'a name carries markup'
    assert targets(TARGETS_PATH.with_name('nope.csv')) == [], 'a missing watchlist is not a crash'
    print(f'ok, {len(rows)} items on the watchlist, dearest '
          f'{max(rows, key=lambda r: r[2])[0]} at {max(r[2] for r in rows):,}')
